### ISSUE TITLE
PredCellTypes download link seems to be outdated

### ISSUE THREAD

**Issue by MikedeKokkie** [weilin-genomics/rSuperCT_models#1]
Greetings, 

I am enthousiastic about the premise of your package, however I have run into an issue:

```
> CellTypeData <- PredCellTypes(CellTypeData, species = 'human', model = 'generic_38CellTypes', results.dir = './models')
trying URL 'https://raw.githubusercontent.com/weilin-genomics/rSuperCT_models/blob/master/generic_38CellTypes/generic_38CellTypes.tar.gz'
cannot open URL 'https://raw.githubusercontent.com/weilin-genomics/rSuperCT_models/blob/master/generic_38CellTypes/generic_38CellTypes.tar.gz': HTTP status was '404 Not Found'Error in download.file(url = paste0("https://raw.githubusercontent.com/weilin-genomics/rSuperCT_models/blob/master/",  : 
  cannot open URL 'https://raw.githubusercontent.com/weilin-genomics/rSuperCT_models/blob/master/generic_38CellTypes/generic_38CellTypes.tar.gz'
```

I've tried replacing the link inside the PredCellTypes function with an updated link (https://github.com/weilin-genomics/rSuperCT_models/blob/master/generic_38celltypes/generic_38celltypes.tar.gz
), sadly to no avail due to the following error:

```
> CellTypeData <- PredCellTypesMike(CellTypeData, species = 'human', model = 'generic_38CellTypes', results.dir = './models')
trying URL 'https://github.com/weilin-genomics/rSuperCT_models/blob/master/generic_38celltypes/generic_38celltypes.tar.gz?raw=true'
Content type 'application/octet-stream' length 8367160 bytes (8.0 MB)
downloaded 8.0 MB

Error in PredCellTypesMike(CellTypeData, species = "human", model = "generic_38CellTypes",  : 
  genes file missing.
```

A fix would be appreciated! 
Greetings,
Mike

**Comment by weilin-genomics** [comment]
thanks for reaching out. I will try to fix the download problem ASAP. 

For now, you may find the downloaded file from rSuperCT_models, unzip it, and put it into the ./models folder. the command will go through.

The local directory structure should be like the this after the unzip.

./model/generic_38celltypes/***.csv

If so, the PredCellTypes will go through. And you can find your predictions in CellTypeData@meta.data$pred_types.

-Wei

**Comment by weilin-genomics** [comment]
@MikedeKokkie Problem solved!

Check the following link:

https://github.com/weilin-genomics/rSuperCT/issues/1#issuecomment-622988203

**Comment by MikedeKokkie** [comment]
@weilin-genomics 
Thank you so much!!!
